version: '3.8'

services:
  aibox-camera:
    build:
      context: ./aibox-camera
      dockerfile: Dockerfile_rknn
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-camera:rknn-${IMAGE_TAG:-main}
    privileged: true
    platform: linux/arm64
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-camera.json
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
      - CORAL_NODE_SHARED_MEMORY_EXPIRE=${CORAL_NODE_SHARED_MEMORY_EXPIRE:-3}
    volumes:
      - /dev:/dev
      - /sys/class/net/wlan0/address:/host_sys/class/net/wlan0/address
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-person:
    build:
      context: ./aibox-person
      dockerfile: Dockerfile_rknn
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-person:rknn-${IMAGE_TAG:-main}
    privileged: true
    platform: linux/arm64
    depends_on:
      - aibox-camera
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-person.json
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    volumes:
      - /dev:/dev
      - /sys/class/net/wlan0/address:/host_sys/class/net/wlan0/address
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-face:
    build:
      context: ./aibox-face
      dockerfile: Dockerfile_rknn
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-face:rknn-${IMAGE_TAG:-main}
    privileged: true
    platform: linux/arm64
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-face.json
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    volumes:
      - /dev:/dev
      - /sys/class/net/wlan0/address:/host_sys/class/net/wlan0/address
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-record:
    build:
      context: ./aibox-record
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-record:rknn-${IMAGE_TAG:-main}
    privileged: true
    platform: linux/arm64
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-record.json
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    volumes:
      - /dev:/dev
      - /sys/class/net/wlan0/address:/host_sys/class/net/wlan0/address
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-report:
    build:
      context: ./aibox-report
      dockerfile: Dockerfile_rknn
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-report:rknn-${IMAGE_TAG:-main}
    privileged: true
    platform: linux/arm64
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-report.json
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
      - MQTT_BROKER=${MQTT_BROKER:-127.0.0.1}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME:-admin}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-admin}
    depends_on:
      - aibox-face
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - /sys/class/net/wlan0/address:/host_sys/class/net/wlan0/address
      - /sys/class/gpio:/sys/class/gpio
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-web:
    build:
      context: ./aibox-web
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-web:rknn-${IMAGE_TAG:-main}
    platform: linux/arm64
    network_mode: host
    privileged: true
    restart: unless-stopped
  
  aibox-nginx:
    image: ${DOCKER_MIRROR:-docker.io}/library/nginx:latest
    network_mode: host
    volumes:
      - ./aibox-nginx.conf:/etc/nginx/conf.d/aibox.conf
    restart: unless-stopped
  
  aibox-mqtt:
    image: ${DOCKER_MIRROR:-docker.io}/library/eclipse-mosquitto:latest
    network_mode: host
    volumes:
      - ./mosquitto:/mosquitto
    restart: unless-stopped