version: '3.8'

services:
  aibox-camera:
    build:
      context: ./aibox-camera
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-camera:rt-${IMAGE_TAG:-v0.1.0}
    privileged: true
    network_mode: host
    environment:
      - MODEL_TYPE=rt
      - LOGURU_LEVEL=INFO
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-camera.json
      - ACTIVATION_CODE=${ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped # 如果服务退出，则除非手动停止，否则总是重启

  aibox-person:
    build:
      context: ./aibox-person
      dockerfile: Dockerfile_rt
    image: ${USERNAME:-local}/aibox-person:rt-${IMAGE_TAG:-v0.1.0}
    privileged: true
    depends_on:
      - aibox-camera
    network_mode: host
    environment:
      - MODEL_TYPE=rt
      - WEIGHTS_REMOTE_HOST=https://nbstore.oss-cn-shanghai.aliyuncs.com/aibox-pro2/nx/weights/
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-person.json
      - ACTIVATION_CODE=${ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-face:
    build:
      context: ./aibox-face
      dockerfile: Dockerfile_rt
    image: ${USERNAME:-local}/aibox-face:rt-${IMAGE_TAG:-v0.1.0}
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rt
      - WEIGHTS_REMOTE_HOST=https://nbstore.oss-cn-shanghai.aliyuncs.com/aibox-pro2/nx/weights/
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-face.json
      - ACTIVATION_CODE=${ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-record:
    build:
      context: ./aibox-record
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-record:rt-${IMAGE_TAG:-v0.1.0}
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rt
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-record.json
      - ACTIVATION_CODE=${ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-report:
    build:
      context: ./aibox-report
      dockerfile: Dockerfile_rt
    image: ${USERNAME:-local}/aibox-report:rt-${IMAGE_TAG:-v0.1.0}
    privileged: true
    environment:
      - MODEL_TYPE=rt
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-report.json
      - ACTIVATION_CODE=${ACTIVATION_CODE:-}
    depends_on:
      - aibox-face
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-web:
    build:
      context: ./aibox-web
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-web:rt-${IMAGE_TAG:-v0.1.0}
    privileged: true
    ports:
      - 3000:3000
    volumes:
      - $HOME/.coral:/root/.coral
    restart: unless-stopped