version: '3.8'

services:
  aibox-camera:
    build:
      context: ./aibox-camera
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-camera:${IMAGE_TAG:-v0.1.0}
    privileged: true
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-camera.json
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-person:
    build:
      context: ./aibox-person
      dockerfile: Dockerfile_rknn
    image: ${USERNAME:-local}/aibox-person:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    depends_on:
      - aibox-camera
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - WEIGHTS_REMOTE_HOST=https://nbstore.oss-cn-shanghai.aliyuncs.com/aibox-pro2/rknn/weights/
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-person.json
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-face:
    build:
      context: ./aibox-face
      dockerfile: Dockerfile_rknn
    image: ${USERNAME:-local}/aibox-face:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - WEIGHTS_REMOTE_HOST=https://nbstore.oss-cn-shanghai.aliyuncs.com/aibox-pro2/rknn/weights/
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-face.json
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-record:
    build:
      context: ./aibox-record
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-record:${IMAGE_TAG:-v0.1.0}
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-record.json
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-report:
    build:
      context: ./aibox-report
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-report:${IMAGE_TAG:-v0.1.0}
    privileged: true
    environment:
      - MODEL_TYPE=rknn
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-report.json
    depends_on:
      - aibox-face
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-web:
    build:
      context: ./aibox-web
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-web:${IMAGE_TAG:-v0.1.0}
    network_mode: host
    environment:
      - NEXT_PUBLIC_AIBOX_HOST=http://10.184.13.118
    privileged: true
    volumes:
      - $HOME/.coral:/root/.coral