version: '3.8'

services:
  aibox-camera:
    build:
      context: ./aibox-camera
      dockerfile: Dockerfile_rknn
    image: ${USERNAME:-local}/aibox-camera:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    platform: linux/arm64
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-camera.json
      - CORAL_NODE_ACTIVATION_CODE=${CORAL_NODE_ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-person:
    build:
      context: ./aibox-person
      dockerfile: Dockerfile_rknn
    image: ${USERNAME:-local}/aibox-person:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    platform: linux/arm64
    depends_on:
      - aibox-camera
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-person.json
      - CORAL_NODE_ACTIVATION_CODE=${CORAL_NODE_ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-face:
    build:
      context: ./aibox-face
      dockerfile: Dockerfile_rknn
    image: ${USERNAME:-local}/aibox-face:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    platform: linux/arm64
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-face.json
      - CORAL_NODE_ACTIVATION_CODE=${CORAL_NODE_ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-record:
    build:
      context: ./aibox-record
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-record:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    platform: linux/arm64
    depends_on:
      - aibox-person
    network_mode: host
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-record.json
      - CORAL_NODE_ACTIVATION_CODE=${CORAL_NODE_ACTIVATION_CODE:-}
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-report:
    build:
      context: ./aibox-report
      dockerfile: Dockerfile_rknn
    image: ${USERNAME:-local}/aibox-report:rknn-${IMAGE_TAG:-v0.1.0}
    privileged: true
    platform: linux/arm64
    environment:
      - MODEL_TYPE=rknn
      - LOGURU_LEVEL=INFO
      - CONFIG_REMOTE_HOST=${CONFIG_REMOTE_HOST:-https://nbstore.oss-cn-shanghai.aliyuncs.com/coral-aibox/rknn/}
      - CORAL_NODE_CONFIG_PATH=/root/.coral/aibox/configs/aibox-report.json
      - CORAL_NODE_ACTIVATION_CODE=${CORAL_NODE_ACTIVATION_CODE:-}
      - MQTT_BROKER=${MQTT_BROKER:-127.0.0.1}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME:-admin}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-admin}
    depends_on:
      - aibox-face
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-web:
    build:
      context: ./aibox-web
      dockerfile: Dockerfile
    image: ${USERNAME:-local}/aibox-web:rknn-${IMAGE_TAG:-v0.1.0}
    platform: linux/arm64
    network_mode: host
    privileged: true
    volumes:
      - $HOME/.coral:/root/.coral
    restart: unless-stopped