version: '3.8'

services:
  aibox-camera:
    build:
      context: ./aibox-camera
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-camera:${IMAGE_TAG:-main}
    privileged: true
    network_mode: host
    environment:
      - CORAL_NODE_SHARED_MEMORY_EXPIRE=${CORAL_NODE_SHARED_MEMORY_EXPIRE:-5}
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
      - LOGURU_LEVEL=INFO
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped # 如果服务退出，则除非手动停止，否则总是重启

  aibox-person:
    build:
      context: ./aibox-person
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-person:${IMAGE_TAG:-main}
    environment:
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    privileged: true
    depends_on:
      - aibox-camera
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-face:
    build:
      context: ./aibox-face
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-face:${IMAGE_TAG:-main}
    environment:
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-record:
    build:
      context: ./aibox-record
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-record:${IMAGE_TAG:-main}
    environment:
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-report:
    build:
      context: ./aibox-report
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-report:${IMAGE_TAG:-main}
    environment:
      - CORAL_NODE_ACTIVATION_CODE_PATH=/root/.rock/activate_code/device
    privileged: true
    depends_on:
      - aibox-face
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral 
      - $HOME/.rock/activate_code:/root/.rock/activate_code
    restart: unless-stopped

  aibox-web:
    build:
      context: ./aibox-web
      dockerfile: Dockerfile
    image: ${DOCKER_MIRROR:-docker.io}/${DOCKER_USERNAME:-loopeai}/aibox-web:${IMAGE_TAG:-main}
    ports:
      - 3000:3000
    restart: unless-stopped

  aibox-nginx:
    image: ${DOCKER_MIRROR:-docker.io}/library/nginx:latest
    network_mode: host
    volumes:
      - ./aibox-nginx.conf:/etc/nginx/conf.d/aibox.conf
    restart: unless-stopped

  aibox-mqtt:
    image: ${DOCKER_MIRROR:-docker.io}/library/eclipse-mosquitto:latest
    network_mode: host
    volumes:
      - ./mosquitto:/mosquitto
    restart: unless-stopped