version: '3.8'

services:
  aibox-camera:
    build:
      context: ./aibox-camera
      dockerfile: Dockerfile
    image: ${USERNAME}/aibox-camera:${IMAGE_TAG}
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped # 如果服务退出，则除非手动停止，否则总是重启

  aibox-person:
    build:
      context: ./aibox-person
      dockerfile: Dockerfile_rt
    image: ${USERNAME}/aibox-person:rt-${IMAGE_TAG}
    privileged: true
    depends_on:
      - aibox-camera
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-face:
    build:
      context: ./aibox-face
      dockerfile: Dockerfile_rt
    image: ${USERNAME}/aibox-face:rt-${IMAGE_TAG}
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-record:
    build:
      context: ./aibox-record
      dockerfile: Dockerfile
    image: ${USERNAME}/aibox-record:${IMAGE_TAG}
    privileged: true
    depends_on:
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-report:
    build:
      context: ./aibox-report
      dockerfile: Dockerfile
    image: ${USERNAME}/aibox-report:${IMAGE_TAG}
    privileged: true
    depends_on:
      - aibox-face
      - aibox-person
    network_mode: host
    volumes:
      - /dev:/dev
      - $HOME/.coral:/root/.coral
    restart: unless-stopped

  aibox-web:
    build:
      context: ./aibox-web
      dockerfile: Dockerfile
    image: ${USERNAME}/aibox-web:${IMAGE_TAG}
    privileged: true
    ports:
      - 3000:3000
    volumes:
      - $HOME/.coral:/root/.coral