FROM bboyhanat/ubuntu2004-ros2foxy-rknn150:v1.4

ENV TZ="Asia/Shanghai"
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
# opencv 相关安装so文件
# RUN apt-get update && apt-get install -y libgl1

WORKDIR /workspace



RUN python3 -m pip install -U pip setuptools wheel && \
    pip3 install poetry==1.8.2

COPY poetry.lock pyproject.toml /workspace/
ADD libs/* /workspace/libs/
RUN poetry install --without rt,onnx && \
    rm -rf /root/.local
ADD aarch64 /workspace/aarch64
RUN cp aarch64/usr/bin/* /usr/bin && cp aarch64/usr/libs/* /usr/lib && restart_rknn.sh

COPY . .

CMD cd aibox-person && sleep 5 && poetry run python3 node.py