FROM bboyhanat/ubuntu2004-ros2foxy-rknn150:v1.4

ENV TZ="Asia/Shanghai"
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
RUN apt-get update && apt-get install -y libgl1 libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
RUN LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD

WORKDIR /workspace

RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip3 config set global.timeout 300 && \
    pip3 config set install.trusted-host pypi.tuna.tsinghua.edu.cn

RUN python3 -m pip install -U pip setuptools wheel && \
    pip3 install poetry==1.8.2 

COPY poetry.lock pyproject.toml /workspace/
RUN poetry install --with rknn && \
    rm -rf /root/.local

COPY . .

CMD cd aibox-camera && poetry run python3 node.py