name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-rknn:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: /var/lib/docker
      #     key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.yaml') }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images for rknn
        run: |
          USERNAME=${{ secrets.DOCKERHUB_USERNAME }} IMAGE_TAG=${{ steps.extract_tag.outputs.TAG_NAME }} docker compose -f docker-compose-rknn.yml build
          USERNAME=${{ secrets.DOCKERHUB_USERNAME }} IMAGE_TAG=${{ steps.extract_tag.outputs.TAG_NAME }} docker compose -f docker-compose-rknn.yml push
        env:
          IMAGE_TAG: ${{ steps.extract_tag.outputs.TAG_NAME }}
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  build-and-push-rt:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: /var/lib/docker
      #     key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.yaml') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images for rt
        run: |
          USERNAME=${{ secrets.DOCKERHUB_USERNAME }} IMAGE_TAG=${{ steps.extract_tag.outputs.TAG_NAME }} docker compose -f docker-compose-rt.yml build
          USERNAME=${{ secrets.DOCKERHUB_USERNAME }} IMAGE_TAG=${{ steps.extract_tag.outputs.TAG_NAME }} docker compose -f docker-compose-rt.yml push
        env:
          IMAGE_TAG: ${{ steps.extract_tag.outputs.TAG_NAME }}
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}