FROM bboyhanat/jetson-nano-cu102-trt7:v1.7

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get install -y --no-install-recommends \
    python3.8 python3.8-dev python3-pip python3.8-venv && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# 清理缓存
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV TZ="Asia/Shanghai"
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
# opencv 相关安装so文件
# RUN apt-get update && apt-get install -y libgl1

WORKDIR /workspace

RUN python3 -m pip install -U pip setuptools wheel && \
    pip3 install poetry==1.8.2

RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip3 config set global.timeout 300 && \
    pip3 config set install.trusted-host pypi.tuna.tsinghua.edu.cn


COPY poetry.lock pyproject.toml /workspace/
RUN poetry install --without onnx,rknn && \
    rm -rf /root/.cache && \
    rm -rf /root/.local

COPY . .

CMD cd aibox-face && poetry run python3 node.py